import { EventInfo, ZoneInfo } from '../types';

export const HERO_SLIDES = [
  {
    id: 1, eventId: 1,
    name: "ANH TRAI SAY HI",
    subtitle: "ATSH CONCERT 2026 — ĐÊM DIỄN CUỐI NĂM",
    artists: "HIEUTHUHAI · Quân A.P · Rhyder · Erik · Isaac · Negav",
    date: "14 THG 6, 2026", time: "18:00",
    venue: "Sân Vận Động Mỹ Đình", city: "Hà Nội",
    price: "800.000",
    image: "https://images.unsplash.com/photo-1566477712363-3c75dd39b416?w=1800&h=900&fit=crop&auto=format&q=80",
    accentColor: "#FF2D20", tag: "SOLD OUT NHANH",
  },
  {
    id: 2, eventId: 2,
    name: "ANH TRAI VƯỢT NGÀN CHÔNG GAI",
    subtitle: "THE GRAND FINALE — HÀNH TRÌNH KHÉP LẠI",
    artists: "Sơn Tùng M-TP · Noo Phước Thịnh · Đức Phúc · Dương Triệu Vũ",
    date: "22 THG 6, 2026", time: "19:00",
    venue: "Nhà Thi Đấu Quân Khu 7", city: "TP. Hồ Chí Minh",
    price: "600.000",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1800&h=900&fit=crop&auto=format&q=80",
    accentColor: "#CCFF00", tag: "HOT",
  },
  {
    id: 3, eventId: 5,
    name: "CHỊ ĐẸP ĐẠP GIÓ RẼ SÓNG",
    subtitle: "GRAND TOUR 2026 — QUYỀN LỰC TRÊN SÂN KHẤU",
    artists: "Hồ Ngọc Hà · Thu Minh · Mỹ Linh · Uyên Linh · Tóc Tiên",
    date: "12 THG 7, 2026", time: "19:30",
    venue: "Cung Thể Thao Quần Ngựa", city: "Hà Nội",
    price: "750.000",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1800&h=900&fit=crop&auto=format&q=80",
    accentColor: "#C084FC", tag: "GẦN HẾT VÉ",
  },
  {
    id: 4, eventId: 3,
    name: "EM XINH SAY HI",
    subtitle: "DEBUT CONCERT — LẦN ĐẦU TIÊN TRÊN SÂN KHẤU LỚN",
    artists: "Wren Evans · Tage · Lena · Phúc Du · Tăng Duy Tân",
    date: "05 THG 7, 2026", time: "20:00",
    venue: "GEM Center", city: "TP. Hồ Chí Minh",
    price: "450.000",
    image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=1800&h=900&fit=crop&auto=format&q=80",
    accentColor: "#38BDF8", tag: "MỚI MỞ BÁN",
  },
  {
    id: 5, eventId: 6,
    name: "AFTERPARTY EDM FESTIVAL",
    subtitle: "INTERNATIONAL NIGHT — DJ SNAKE & MORE",
    artists: "DJ Snake · Lost Frequencies · KSHMR · Alesso",
    date: "02 THG 8, 2026", time: "21:00",
    venue: "SECC", city: "TP. Hồ Chí Minh",
    price: "1.200.000",
    image: "https://images.unsplash.com/photo-1599739291127-15c456e459ee?w=1800&h=900&fit=crop&auto=format&q=80",
    accentColor: "#CCFF00", tag: "QUỐC TẾ",
  },
];

export const CATEGORIES = ["Tất cả", "Nhạc Pop", "R&B / Soul", "Rap / Hip-Hop", "Rock", "EDM", "Comedy", "Classical"];

export const EVENTS: EventInfo[] = [
  {
    id: 1, name: "ANH TRAI SAY HI", subtitle: "ATSH Concert 2026",
    artist: "HIEUTHUHAI, Quân A.P, Rhyder, Erik, Isaac",
    date: "14 THG 6, 2026", time: "18:00", venue: "Sân Vận Động Mỹ Đình", city: "Hà Nội",
    price: "800.000", category: "Nhạc Pop",
    image: "https://images.unsplash.com/photo-1566477712363-3c75dd39b416?w=800&h=600&fit=crop&auto=format",
    tag: "HOT", tagStyle: "bg-[#FF2D20] text-white", sold: 93, featured: true,
    description: "Đêm diễn cuối năm của chương trình Anh Trai Say Hi với sự tham gia của toàn bộ dàn nghệ sĩ. Khán giả sẽ được thưởng thức những màn trình diễn đỉnh cao, kết hợp âm nhạc sôi động và hình ảnh sân khấu hoành tráng.",
    artistList: [
      { name: "HIEUTHUHAI", role: "Nghệ sĩ chính" }, { name: "Quân A.P", role: "Nghệ sĩ chính" },
      { name: "Rhyder", role: "Khách mời" }, { name: "Erik", role: "Khách mời" },
      { name: "Isaac", role: "Khách mời" }, { name: "Negav", role: "Khách mời" },
    ],
  },
  {
    id: 2, name: "RAP VIỆT ALL-STARS", subtitle: "Concert Rap Lớn Nhất Năm",
    artist: "Binz, Đen Vâu, MCK, Obito, Tlinh",
    date: "22 THG 6, 2026", time: "18:00", venue: "Nhà Thi Đấu Quân Khu 7", city: "TP. Hồ Chí Minh",
    price: "500.000", category: "Rap / Hip-Hop",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=700&h=500&fit=crop&auto=format",
    tag: "MỚI MỞ BÁN", tagStyle: "bg-[#CCFF00] text-black", sold: 62, featured: false,
    description: "Tập hợp những cái tên đình đám nhất của làng rap Việt Nam trong một đêm nhạc không thể bỏ qua. Đây là lần đầu tiên các nghệ sĩ cùng đứng chung sân khấu.",
    artistList: [
      { name: "Binz", role: "Nghệ sĩ chính" }, { name: "Đen Vâu", role: "Nghệ sĩ chính" },
      { name: "MCK", role: "Nghệ sĩ chính" }, { name: "Obito", role: "Khách mời" },
      { name: "Tlinh", role: "Khách mời" },
    ],
  },
  {
    id: 3, name: "BINZ × TOULIVER LIVE", subtitle: "Live In Concert",
    artist: "Binz, Touliver",
    date: "05 THG 7, 2026", time: "20:00", venue: "GEM Center", city: "TP. Hồ Chí Minh",
    price: "650.000", category: "Rap / Hip-Hop",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=700&h=500&fit=crop&auto=format",
    tag: "GẦN HẾT VÉ", tagStyle: "bg-orange-500 text-white", sold: 94, featured: false,
    description: "Một đêm nhạc kết hợp rap và electronic độc đáo từ hai nghệ sĩ tài năng nhất Việt Nam. Âm nhạc live sẽ tạo ra một không gian trải nghiệm hoàn toàn khác biệt.",
    artistList: [{ name: "Binz", role: "Nghệ sĩ chính" }, { name: "Touliver", role: "Producer / DJ" }],
  },
  {
    id: 4, name: "ĐEN VÂU — TRỜI ƠI!", subtitle: "Đêm Nhạc Trực Tiếp",
    artist: "Đen Vâu",
    date: "12 THG 7, 2026", time: "19:00", venue: "Cung TT Quần Ngựa", city: "Hà Nội",
    price: "400.000", category: "Rap / Hip-Hop",
    image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=700&h=500&fit=crop&auto=format",
    tag: null, tagStyle: "", sold: 45, featured: false,
    description: "Đen Vâu trở lại với đêm nhạc solo đầy cảm xúc tại Hà Nội, mang đến những ca khúc đã đồng hành cùng hàng triệu người nghe.",
    artistList: [{ name: "Đen Vâu", role: "Nghệ sĩ chính" }],
  },
  {
    id: 5, name: "MỸ TÂM TOUR 2026", subtitle: "Hoa Hồng Có Gai",
    artist: "Mỹ Tâm",
    date: "19 THG 7, 2026", time: "19:30", venue: "Nhà Hát Hòa Bình", city: "TP. Hồ Chí Minh",
    price: "850.000", category: "Nhạc Pop",
    image: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=700&h=500&fit=crop&auto=format",
    tag: "VIP", tagStyle: "bg-purple-600 text-white", sold: 71, featured: false,
    description: "Mỹ Tâm trở lại với world tour đầy hoành tráng sau nhiều năm chờ đợi. Đêm diễn sẽ kể lại hành trình âm nhạc hơn 20 năm của người phụ nữ mạnh mẽ nhất Vpop.",
    artistList: [{ name: "Mỹ Tâm", role: "Nghệ sĩ chính" }],
  },
  {
    id: 6, name: "AFTERPARTY FESTIVAL", subtitle: "EDM & Electronic Night",
    artist: "DJ Snake, Lost Frequencies, KSHMR",
    date: "02 THG 8, 2026", time: "21:00", venue: "SECC", city: "TP. Hồ Chí Minh",
    price: "1.200.000", category: "EDM",
    image: "https://images.unsplash.com/photo-1565035010268-a3816f98589a?w=700&h=500&fit=crop&auto=format",
    tag: "QUỐC TẾ", tagStyle: "bg-blue-600 text-white", sold: 58, featured: false,
    description: "Festival EDM quốc tế lớn nhất từ trước đến nay tại Việt Nam. Bốn DJ hàng đầu thế giới sẽ cùng khuấy động Sài Gòn trong một đêm không ngủ.",
    artistList: [
      { name: "DJ Snake", role: "DJ chính" }, { name: "Lost Frequencies", role: "DJ chính" },
      { name: "KSHMR", role: "Khách mời" }, { name: "Alesso", role: "Khách mời" },
    ],
  },
  {
    id: 7, name: "MCK & OBITO", subtitle: "Anh Đã Ổn Hơn Concert",
    artist: "MCK, Obito",
    date: "26 THG 7, 2026", time: "19:30", venue: "TT Hội Nghị 8 Hoàng Diệu", city: "Đà Nẵng",
    price: "450.000", category: "Rap / Hip-Hop",
    image: "https://images.unsplash.com/photo-1563841930606-67e2bce48b78?w=700&h=500&fit=crop&auto=format",
    tag: null, tagStyle: "", sold: 33, featured: false,
    description: "MCK và Obito hội ngộ trong đêm concert đặc biệt tại Đà Nẵng, mang lại những khoảnh khắc âm nhạc chữa lành và đầy năng lượng.",
    artistList: [{ name: "MCK", role: "Nghệ sĩ chính" }, { name: "Obito", role: "Nghệ sĩ chính" }],
  },
  {
    id: 8, name: "MONO — WAITING FOR WINTER", subtitle: "First Solo Concert",
    artist: "MONO",
    date: "09 THG 8, 2026", time: "19:00", venue: "Nhà Hát Lớn Hà Nội", city: "Hà Nội",
    price: "600.000", category: "R&B / Soul",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=700&h=500&fit=crop&auto=format",
    tag: "MỚI", tagStyle: "bg-[#CCFF00] text-black", sold: 21, featured: false,
    description: "MONO ra mắt concert solo đầu tiên trong sự nghiệp tại một trong những sân khấu danh giá nhất Hà Nội. Một đêm nhạc R&B đầy cảm xúc.",
    artistList: [{ name: "MONO", role: "Nghệ sĩ chính" }],
  },
];

export const ZONES: ZoneInfo[] = [
  { id: "sky",      name: "SKY LOUNGE",  price: 8000000, color: "#CCFF00", available: 45,  type: "Seating"  },
  { id: "svip-a",   name: "SVIP — A",    price: 5000000, color: "#FF2D20", available: 23,  type: "Seating"  },
  { id: "svip-b",   name: "SVIP — B",    price: 5000000, color: "#FF2D20", available: 31,  type: "Seating"  },
  { id: "vip-a",    name: "VIP — A",     price: 4000000, color: "#C084FC", available: 87,  type: "Seating"  },
  { id: "vip-b",    name: "VIP — B",     price: 4000000, color: "#C084FC", available: 94,  type: "Seating"  },
  { id: "fz-1a",    name: "FANZONE 1A",  price: 1200000, color: "#38BDF8", available: 312, type: "Standing" },
  { id: "fz-1b",    name: "FANZONE 1B",  price: 1200000, color: "#38BDF8", available: 289, type: "Standing" },
  { id: "fz-2a",    name: "FANZONE 2A",  price: 1000000, color: "#60A5FA", available: 421, type: "Standing" },
  { id: "fz-2b",    name: "FANZONE 2B",  price: 1000000, color: "#60A5FA", available: 398, type: "Standing" },
  { id: "cat1a",    name: "CAT 1A",      price: 1500000, color: "#F97316", available: 156, type: "Seating"  },
  { id: "cat1b",    name: "CAT 1B",      price: 1500000, color: "#F97316", available: 143, type: "Seating"  },
  { id: "cat2a",    name: "CAT 2A",      price: 1200000, color: "#FB923C", available: 234, type: "Seating"  },
  { id: "cat2b",    name: "CAT 2B",      price: 1200000, color: "#FB923C", available: 267, type: "Seating"  },
  { id: "ozone",    name: "OZONE",       price: 1500000, color: "#34D399", available: 89,  type: "Standing" },
];

export const UPCOMING = [
  { name: "ANH TRAI SAY HI",    date: "14/06", city: "Hà Nội",   price: "800.000đ",   cat: "POP", id: 1 },
  { name: "RAP VIỆT ALL-STARS", date: "22/06", city: "TP.HCM",   price: "500.000đ",   cat: "RAP", id: 2 },
  { name: "BINZ × TOULIVER",    date: "05/07", city: "TP.HCM",   price: "650.000đ",   cat: "RAP", id: 3 },
  { name: "ĐEN VÂU — TRỜI ƠI!",date: "12/07", city: "Hà Nội",   price: "400.000đ",   cat: "RAP", id: 4 },
  { name: "MỸ TÂM TOUR 2026",   date: "19/07", city: "TP.HCM",   price: "850.000đ",   cat: "POP", id: 5 },
  { name: "MCK & OBITO",        date: "26/07", city: "Đà Nẵng",  price: "450.000đ",   cat: "RAP", id: 7 },
];
